### ISSUE TITLE
Compile Error on Debian

### ISSUE THREAD

**Issue by ethought** [qtumproject/qtum#358]
./autogen.sh
./configure --with-incompatible-bdb
./make -j2

...
CXX      cpp-ethereum/libethereum/libbitcoin_common_a-ExtVM.o
In file included from /usr/include/boost/optional.hpp:15:0,
                 from /usr/include/boost/format/internals.hpp:20,
                 from /usr/include/boost/format.hpp:38,
                 from /usr/include/boost/math/policies/error_handling.hpp:31,
                 from /usr/include/boost/multiprecision/detail/default_ops.hpp:9,
                 from /usr/include/boost/multiprecision/detail/generic_interconvert.hpp:9,
                 from /usr/include/boost/multiprecision/number.hpp:22,
                 from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from ./cpp-ethereum/libdevcore/Common.h:51,
                 from ./cpp-ethereum/libethcore/Common.h:28,
                 from cpp-ethereum/libethereum/ExtVM.h:26,
                 from cpp-ethereum/libethereum/ExtVM.cpp:22:
/usr/include/boost/optional/optional.hpp: In instantiation of ‘void boost::optional_detail::optional_base<T>::construct(boost::optional_detail::optional_base<T>::argument_type) [with T = dev::eth::owning_bytes_ref; boost::optional_detail::optional_base<T>::argument_type = const dev::eth::owning_bytes_ref&]’:
/usr/include/boost/optional/optional.hpp:230:20:   required from ‘boost::optional_detail::optional_base<T>::optional_base(boost::optional_detail::optional_base<T>::argument_type) [with T = dev::eth::owning_bytes_ref; boost::optional_detail::optional_base<T>::argument_type = const dev::eth::owning_bytes_ref&]’
/usr/include/boost/optional/optional.hpp:526:46:   required from ‘boost::optional<T>::optional(boost::optional<T>::argument_type) [with T = dev::eth::owning_bytes_ref; boost::optional<T>::argument_type = const dev::eth::owning_bytes_ref&]’
cpp-ethereum/libethereum/ExtVM.cpp:108:22:   required from here
/usr/include/boost/optional/optional.hpp:346:8: error: use of deleted function ‘dev::eth::owning_bytes_ref::owning_bytes_ref(const dev::eth::owning_bytes_ref&)’
        new (m_storage.address()) internal_type(val) ;
        ^
In file included from cpp-ethereum/libethereum/ExtVM.h:27:0,
                 from cpp-ethereum/libethereum/ExtVM.cpp:22:
./cpp-ethereum/libevm/ExtVMFace.h:72:2: note: declared here
  owning_bytes_ref(owning_bytes_ref const&) = delete;
  ^
Makefile:7968: recipe for target 'cpp-ethereum/libethereum/libbitcoin_common_a-ExtVM.o' failed
make[2]: *** [cpp-ethereum/libethereum/libbitcoin_common_a-ExtVM.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by Earlz** [comment]
Which version of Debian and what is your version of Boost, is it compiled or from packages?

**Comment by ethought** [comment]
Debian 8.9
Boost Version: 1.55.0.2 (from packages)

**Comment by Earlz** [comment]
That version of Boost is pretty ancient (2013) so I imagine that has something to do with it. There are ways to build and statically link the dependencies for Qtum, but I personally don't have any experience with it. I'd research how to use Bitcoin 0.14 on Debian 8.9, and/or learn how to make Gitian builds if you're insistent on compiling it yourself. We do have pre-compiled versions of Qtum Core that work on Debian 8.9 on the release page

**Comment by ethought** [comment]
Thanks will try a release version.
